### ISSUE TITLE
Visual-Enhanced Learning Loss Calculation

### ISSUE THREAD

**Issue by tyz1994** [Weili-NLP/UNIMO-G#5]
Thanks for sharing this great work! 

Learning a visual token that corresponds to latent features is an interesting idea. I'd like to know more details about the $L_{attn}$. There are many cross-attention layers in the UNet, which of them are selected to calculate $CA(z_t,v)$?

**Comment by Weili-NLP** [comment]
We utilize all cross-attention layers by averaging their attention scores. Perhaps a more fine-grained selection could further enhance performance. We leave this for future work.

**Comment by tyz1994** [comment]
Thank you!
